# Generated by Django 2.2.28 on 2026-03-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentReason', models.CharField(max_length=132)),
                ('visitType', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual')], max_length=20)),
                ('appointmentDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('passwordHash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('nhsNumber', models.CharField(max_length=20, unique=True)),
                ('parentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careorbitapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visitID', models.AutoField(primary_key=True, serialize=False)),
                ('visitType', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual')], max_length=20)),
                ('summary', models.TextField()),
                ('visitDate', models.DateTimeField()),
                ('appointmentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='careorbitapp.Appointment')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorVisits', to='careorbitapp.User')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientVisits', to='careorbitapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('testID', models.AutoField(primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=255)),
                ('result', models.TextField()),
                ('resultDate', models.DateField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careorbitapp.User')),
                ('visitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careorbitapp.Visit')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordID', models.AutoField(primary_key=True, serialize=False)),
                ('documentType', models.CharField(choices=[('tests', 'Tests'), ('visitHistory', 'Visit History'), ('notes', 'Notes'), ('meds', 'Medications'), ('general', 'General')], max_length=20)),
                ('fileUrl', models.CharField(max_length=500)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careorbitapp.User')),
                ('visitID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careorbitapp.Visit')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medicationID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('needsRefill', models.BooleanField(default=False)),
                ('prescribedAt', models.DateField()),
                ('doctorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicationsPrescribed', to='careorbitapp.User')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicationsReceived', to='careorbitapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('noteID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careorbitapp.User')),
                ('visitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careorbitapp.Visit')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='careorbitapp.User'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientAppointments', to='careorbitapp.User'),
        ),
    ]
