# Generated by Django 2.2.28 on 2026-03-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careorbitapp', '0002_auto_20260303_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
