# Generated by Django 2.2.28 on 2026-03-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careorbitapp', '0003_auto_20260303_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('appointmentDuration', models.IntegerField(default=30)),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='careorbitapp.User')),
            ],
            options={
                'unique_together': {('doctorID', 'day')},
            },
        ),
    ]
