# Generated by Django 2.2.28 on 2026-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careorbitapp', '0004_auto_20260308_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nhsNumber',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
